//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrosClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarrosClientes()
        {
            this.Citas = new HashSet<Citas>();
        }
    
        public int IdCarroCliente { get; set; }
        public int IdCliente { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public int Anio { get; set; }
        public string Placas { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
    }
}
